### ISSUE TITLE
Export map description to PDF

### ISSUE THREAD

**Issue by waschbeer** [aktionskarten/frontend#26]
According to the map creation wizard, the description provided in step 1 is supposed to be rendered as a backside of the pdf map (second page). This is currently not the case.

(not sure whether this issue belongs here or in the aktionskarten.js repo)

**Comment by iomn** [comment]
As the pdf is rendered in the backend, it should be an issue there. Closing an reopen (see https://github.com/aktionskarten/backend/issues/41 )
